services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      # POSTGRES_USER: ${DB_USER}
      # POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432" 